---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-basic-auth
  namespace: loki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    name: loki-basic-auth # gateway authentication
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: loki-gateway-username
    - secretKey: password
      remoteRef:
        key: loki-gateway-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: canary-basic-auth
  namespace: loki
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    name: canary-basic-auth # canary health checks
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: loki-canary-username
    - secretKey: password
      remoteRef:
        key: loki-canary-password
