apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault-store
spec:
  provider:
    azurekv:
      # PublicCloud, USGovernmentCloud, ChinaCloud, GermanCloud
      environmentType: PublicCloud # default
      authType: WorkloadIdentity
      vaultUrl: "https://azwi-kv-k3s-prod-122025.vault.azure.net/"
      serviceAccountRef:
        name: workload-identity-sa
        namespace: external-secrets-operator
