apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos
resources:
  - workload-identity-sa.yaml
  - cluster-config.yaml
  - external-secret.yaml
  - ingress.yaml
  - tls-certificate.yaml
