apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thanos-receive-tls
  namespace: thanos
spec:
  secretName: thanos-receive-tls
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
  dnsNames:
    - thanos-receive.cloudandklir.com
