apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: thanos
  annotations:
    azure.workload.identity/client-id: "78a41095-a47f-4171-b775-d89118aecc38"
    azure.workload.identity/tenant-id: "7a07eeec-fee1-4167-a709-209e4f54f334"
