apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshPolicy: CreatedOnce
  refreshInterval: "0"
  secretStoreRef:
    name: azure-key-vault-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token # The Kubernetes Secret that will get created (in the "cert-manager" namespace)
    creationPolicy: Owner
  data:
    - secretKey: "api-token" # The name of the key within the Kubernetes Secret
      remoteRef:
        key: cloudflare-api-token # The name of the secret in Azure Key Vault
        # property: api-token # The actual key name in Azure Key Vault
