apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-key-vault-store
  namespace: external-secrets-operator
spec:
  provider:
    azurekv:
      # PublicCloud, USGovernmentCloud, ChinaCloud, GermanCloud
      environmentType: PublicCloud # default
      authType: WorkloadIdentity
      vaultUrl: "https://azwi-kv-e289.vault.azure.net/"
      serviceAccountRef:
        name: workload-identity-sa
