apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: external-secrets-operator
spec:
  provider:
    azurekv:
      # PublicCloud, USGovernmentCloud, ChinaCloud, GermanCloud
      environmentType: PublicCloud # default
