apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: "2213c653-394b-48bd-950f-b90211676432"
    azure.workload.identity/tenant-id: "7a07eeec-fee1-4167-a709-209e4f54f334"
