apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-objstore-config
  namespace: thanos
data:
  objstore.yaml: |
    type: AZURE
    config:
      storage_account: ""
      storage_account_key: ""
      container: ""
      endpoint: ""
      max_retries: 0
