apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-key-vault-store
  target:
    name: renovate-github-token # The name of the Kubernetes secret that will get created (in the "renovate" namespace)
    creationPolicy: Owner
  data:
    - secretKey: renovate-github-token # The name of the key within the Kubernetes secret
      remoteRef:
        key: renovate-github-token # The name of the secret in Azure Key Vault
        # version: provider-key-version   # optional, defaults to latest if omitted
        property: renovate-github-token # The key name in Azure Key Vault secret
