apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflared.yaml
  - cloudflare-tunnel-credentials.yaml
  - superuser-credentials.yaml
