apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thanos
resources:
  - ../../base/thanos/
patches:
  - target:
      kind: HelmRelease
      name: thanos
    patch: |
      - op: add
        path: /spec/valuesFrom
        value:
          - kind: ConfigMap
            name: thanos-cluster-config
            valuesKey: values.yaml
